server:
  port: 8087 # 项目启动的端口

spring:
  profiles:
    active: dev # 默认激活 dev 本地开发环境
  data:
    redis:
      database: 0 # Redis 数据库索引（默认为 0）
      host: 47.108.30.199# Redis 服务器地址
      port: 6379 # Redis 服务器连接端口
      timeout: 5s # 读超时时间
      connect-timeout: 5s # 链接超时时间
      lettuce:
        pool:
          max-active: 200 # 连接池最大连接数
          max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
          min-idle: 0 # 连接池中的最小空闲连接
          max-idle: 10 # 连接池中的最大空闲连接
  rabbitmq:
      host: 47.108.30.199
      port: 5672
      username: guest
      password: guest
      virtual-host: /
      connection-timeout: 5000
      cache:
        channel:
          size: 10
      listener:
        simple:
          acknowledge-mode: manual
          concurrency: 5
          max-concurrency: 10
          prefetch: 50
          retry:
            enabled: true
            max-attempts: 3
            initial-interval: 1000
      publisher-confirm-type: correlated
      publisher-returns: true
mybatis:
  # MyBatis xml 配置文件路径
  mapper-locations: classpath:/mapper/**/*.xml
