server:
  port: 8081 # 项目启动的端口

spring:
  profiles:
    active: dev # 默认激活 dev 本地开发环境
storage:
  type: aliyun # 对象存储类型
  aliyun:
    oss:
      endpoint: oss-cn-hangzhou.aliyuncs.com
      access-key-id: {aliyun.oss.access-key-id}
      access-key-secret: {aliyun.oss.access-key-secret}
      bucket-name: {aliyun.oss.bucket-name}